---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-myapp
  namespace: deployment-strategies
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: henryxilojherrera/democi:20
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5