apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: deployment-strategies
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
